stream_sizes:
- 1
has_dynamic_features:
- false
stream_weights:
- 1
netG:
  _target_: nnsvs.model.LSTMRNN
  in_dim: 368
  out_dim: 1
  hidden_dim: 256
  num_layers: 3
  bidirectional: true
  dropout: 0.3
