stream_sizes:
- 180
- 3
- 1
- 15
has_dynamic_features:
- true
- true
- false
- true
num_windows: 3
stream_weights: null
netG:
  _target_: nnsvs.model.ResF0Conv1dResnet
  in_dim: 372
  out_dim: 199
  hidden_dim: 256
  num_layers: 3
  in_lf0_idx: 323
  out_lf0_idx: 180
  in_lf0_min: 3.4874727725982666
  in_lf0_max: 6.375586032867432
  out_lf0_mean: 5.2847348860052845
  out_lf0_scale: 0.2917796712162183
